include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false           # Неявные объявления
    implicit-dynamic: false         # Неявные переменные
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - avoid_print # Запрет принтов
    - always_use_package_imports # Полное название импорта