include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - avoid_print: true # Запрет принтов
    - always_use_package_imports # Полное название импорта
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - avoid_redundant_argument_values: true # Не передавать параметры, которые указанны по умолчанию
    - depend_on_referenced_packages: false # Явная зависимость от пакетов, на которые вы ссылаетесь
    - lines_longer_than_80_chars: true
    - library_private_types_in_public_api: true
    - use_build_context_synchronously: true