name: spotify_client
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.1.8
  http: ^0.13.5
  shared_preferences: ^2.0.17
  crypto: ^3.0.2
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.0

  intl: ^0.18.0
  freezed_annotation: ^2.2.0
  go_router: ^13.0.0
  get_it: ^7.3.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.2
  connectivity_plus: ^4.0.1
  logging: ^1.2.0
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  generate: true
